use customer_shopping_behavior;
-- 01. what is the total revenue generated by male vs female?
ALTER TABLE customer_behavior
CHANGE `purchase_amount_(usd)` purchase_amount_usd INT;

SELECT gender, SUM(purchase_amount_usd) as revenue
FROM customer_behavior
GROUP BY gender;

-- 02. Which customer used a discount but still spend more than average person amount?
SELECT customer_id, purchase_amount_usd
FROM customer_behavior
Where discount_applied = "Yes" and purchase_amount_usd >= (select avg(purchase_amount_usd) from customer_behavior);

-- 03. Which are the top 5 product with the highest average reveiw rating?
 Select item_purchased, round(avg(review_rating), 2) as avg_rating
 from customer_behavior
 group by item_purchased
 order by avg_rating desc
 limit 5;
 
 -- 04. Compare the average purchase amount between Standard and Express shipping?
 select shipping_type,
 round(avg(purchase_amount_usd), 2) as avg_purchase
 from customer_behavior
 where shipping_type in ('Standard', 'Express')
 group by shipping_type;
 
 -- 05. Do subscribed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers?
 select subscription_status,
 count(customer_id) as total_customers,
 round(avg(purchase_amount_usd),2) as avg_spend,
 round(sum(purchase_amount_usd),2) as total_revenue
 from customer_behavior
 group by subscription_status
 order by total_revenue, avg_spend desc;
 
 -- 06.Which 5 product has the highest percentage of purchases with discount applied?
 select item_purchased,
 round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*)*100, 2) as discount_rate
 from customer_behavior
 group by item_purchased
 order by discount_rate desc
 limit 5;
 
 -- 07. Segment customers into new, returning ande loyal based on their total numbers of previous purchases, 
	-- and show the count of each segment
    with customer_type as(select customer_id, previous_purchases,
    case
        when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'returning'
        else 'Loyal'
        end as customer_segment
    from customer_behavior)
    select customer_segment, count(*) as "No of customers"
    from customer_type
    group by customer_segment
    
    -- 08. What are the top 3 most purchased product within each category ?
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_behavior
)
SELECT 
    customer_segment, 
    COUNT(*) AS "No of customers"
FROM customer_type
GROUP BY customer_segment;

-- second query starts here
SELECT *
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS rank_num
    FROM customer_behavior
    GROUP BY category, item_purchased
) t
WHERE rank_num <= 3; 

-- 09. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe ?
  select subscription_status,
  count(customer_id) as repeat_buyers
  from customer_behavior
  where previous_purchases > 5
  group by subscription_status;
  
  -- 10. What is the revenue contribution of each group?
  select age_group,
  sum(purchase_amount_usd) as total_revenue
  from customer_behavior
  group by age_group
  order by total_revenue desc;
    
        
    
 
         
	
 
 
 



